/** Exporta componentes por unidade */
export { default as AccordionEditorial } from './components/AccordionEditorial'
export { default as Article } from './components/Article/Article'
export { default as AuthorProfile } from './components/AuthorProfile'
export { default as Carousel } from './components/Carousel'
export { default as Copyright } from './components/Copyright'
export { default as Block } from './components/Block'
export { default as Button } from './components/Button'
export { default as Dialog } from './components/Dialog/Dialog'
export { EditArea } from './components/EditArea'
export { default as ErrorPage } from './components/ErrorPage'
export { default as Form } from './components/Form'
export { default as Field } from './components/Field'
export { default as Icon } from './components/Icon'
export { default as Image } from './components/Image'
export { default as Link } from './components/Link'
export { default as Pagination } from './components/Pagination'
export { default as PageBlock } from './components/PageBlock'
export { default as SideMenu } from './components/SideMenu'
export { default as SectionTitle } from './components/SectionTitle'
export { default as SocialMedias } from './components/SocialMedias'
export { default as SocialShare } from './components/Article/Share'
export { default as Subject } from './components/Subject'
export { default as Typography } from './components/Typography'
export { default as TemplateContainer } from './components/Templates/TemplateContainer'

export * from './components/AuthorBio'
export * from './components/Image/parser'
export * from './components/ImageGallery'
export * from './components/Templates'
export * from './styles'

/** Exports com nome estático */
export * as Embeds from './components/Article/Embeds'

/** Export dos types */
export * from './components/Teaser/types'
export * from './styles/templates/types'
export * from './components/SectionTitle/types'