import { PrensaEngineCSSProp } from '../../../types'

type LayoutTypes = {
  active?: boolean
  customColumnCss?: PrensaEngineCSSProp
  default?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '1'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '2'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '2:1'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '2:2'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '3'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '3:1'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '3:2'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '3:3'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '4'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '4:1'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '4:2'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '4:3'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '4:4'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '5'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '5:1'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '5:2'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '5:3'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '5:4'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '5:5'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '6'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '6:1'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '6:2'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '6:3'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '6:4'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '6:5'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '6:6'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '7'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '7:1'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '7:2'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '7:3'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '7:4'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '7:5'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '7:6'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '7:7'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '8'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '8:1'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '8:2'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '8:3'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '8:4'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '8:5'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '8:6'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '8:7'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
  '8:8'?: PrensaEngineCSSProp | [PrensaEngineCSSProp, PrensaEngineCSSProp]
}

export { LayoutTypes }