import * as t from '../types'

type SlotItemsType = t.ItemTypes.ItemDefaultProps[] | []

interface TemplateConfig {
  slotTemplate?: string,
  slotAutoLeftElements?: SlotItemsType,
  slotAutoCenterElements?: SlotItemsType,
  slotAutoRightElements?: SlotItemsType,
  slotManualBottomLeft?: SlotItemsType,
  slotManualBottomCenter?: SlotItemsType,
  slotManualBottomRight?: SlotItemsType,
  slotManualExtra?: SlotItemsType,
  slotManualTopLeft?: SlotItemsType,
  slotManualTopCenter?: SlotItemsType,
  slotManualTopRight?: SlotItemsType,
  slotLeftComponent?: string,
  slotLeftIconValue?: string,
  slotLeftReadMoreEnabled?: boolean,
  slotLeftReadMoreLink?: string,
  slotLeftReadMoreTitle?: string,
  slotLeftTeaserBgColor?: string,
  slotLeftTeaserColor?: string,
  slotLeftLayout?: string,
  slotLeftTitleEnabled?: boolean,
  slotLeftTitleLink?: string,
  slotLeftTitleValue?: string,
  slotCenterComponent?: string,
  slotCenterIconValue?: string,
  slotCenterReadMoreEnabled?: boolean,
  slotCenterReadMoreLink?: string,
  slotCenterReadMoreTitle?: string,
  slotCenterTeaserBgColor?: string,
  slotCenterTeaserColor?: string,
  slotCenterLayout?: string,
  slotCenterTitleEnabled?: boolean,
  slotCenterTitleLink?: string,
  slotCenterTitleValue?: string,
  slotRightComponent?: string,
  slotRightIconValue?: string,
  slotRightReadMoreEnabled?: boolean,
  slotRightReadMoreLink?: string,
  slotRightReadMoreTitle?: string,
  slotRightTeaserBgColor?: string,
  slotRightTeaserColor?: string,
  slotRightLayout?: string,
  slotRightTitleEnabled?: boolean,
  slotRightTitleLink?: string,
  slotRightTitleValue?: string
}

export { SlotItemsType, TemplateConfig }