import Head from 'next/head';
import React from 'react';
import styled from 'styled-components';

import FacebookEmbed, {facebook_amp_script} from '../components/embeds/Facebook';
import InstagramEmbed, {instagram_amp_script} from '../components/embeds/Instagram';
import TwitterEmbed, {twitter_amp_script} from '../components/embeds/Twitter';
import YouTubeEmbed, {youtube_amp_script} from '../components/embeds/YouTube';
import ImageGallery from '../components/ImageGallery';
import styles from '../styles/Home.module.css';

const H1 = styled.h1`
  font-family: inherit;
  color: red;
`;
const Main = styled.main`
  padding: 5rem 1rem;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;

export const config = {amp: true};

export default function Home() {
  // const tweetUrl = 'https://twitter.com/criptofacil/status/1401882624809897985'
  const tweetUrl2 = 'https://twitter.com/criptofacil/status/1401882624809897985?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1401882624809897985%7Ctwgr%5E%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fpublish.twitter.com%2F%3Fquery%3Dhttps3A2F2Ftwitter.com2Fcriptofacil2Fstatus2F1401882624809897985widget%3DTweet';
  const instagramUrl = 'https://www.instagram.com/p/Bz4H4mahyOq';
  const facebookUrl = 'https://www.facebook.com/HugoGloss/posts/10158171335166146';
  const youtubeUrl = 'https://www.youtube.com/watch?v=qJzT_Ww8q9g';
  const imageGallery = [
    {
      caption: 'Tadeu Moreno (médico), Luís Fernando de Barros (fisiologista), Galeano, Volpi, Pablo, Miranda, Igor Gomes, Arboleda, Bruno Alves, Hernanes, Léo, Shaylon, Alejandro Kohan (preparador físico), Gustavo Nepote (preparador de goleiros), Lucas Perri, Pedro Campos (preparador físico), Octavio Ohl (preparador de goleiros), Cristiano Alkinim (roupeiro, Juan Branda (auxiliar técnico), Hernán Crespo e Aílton Rodrigues (massagista); Liziero, Igor Vinícius, Reinaldo, Luan, Gabriel Sara, Rodrigo Nestor, Éder, Luciano, Joao Rojas, William, Paulinho e Orejuelar (Foto: Rubens Chiri / saopaulofc.net)',
      contentId: '1.3658',
      value: 'http://qa.diariodaregiao.com.br/image/policy:1.3658/image.jpg?f=2x1&w=1200'
    },
    {
      caption: 'O cabeleireiro Douglas Negrett montou salão para valorizar estética negra (Guilherme Baffi 7/5/2021)',
      contentId: '1.34636',
      value: 'http://qa.diariodaregiao.com.br/image/policy:1.34636/image.jpg?f=2x1&w=1200'
    },
    {
      caption: 'Isadora, filha da médica Luciana Casseb, com camiseta da marca ',
      contentId: '1.34723',
      value: 'http://qa.diariodaregiao.com.br/image/policy:1.34723/image.jpg?f=2x1&w=1200'
    }
  ];
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {twitter_amp_script}
        {instagram_amp_script}
        {facebook_amp_script}
        {youtube_amp_script}
      </Head>

      <Main>
        <H1>Videos Youtube</H1>
        <YouTubeEmbed url={youtubeUrl} />
        <YouTubeEmbed url={youtubeUrl} />
        <H1>Componente aqui</H1>
        <ImageGallery items={imageGallery} />
        <TwitterEmbed url={tweetUrl2} />
        <InstagramEmbed url={instagramUrl} />
        <FacebookEmbed url={facebookUrl} />
      </Main>
    </div>
  );
}
