export { align } from './align'
export { border } from './border'
export { dimensions } from './dimensions'
export { height } from './height'
export { margin } from './margin'
export { padding } from './padding'
export { getColor } from './color'