name: Pull Request Check

on:
  pull_request: 
    paths: 
      - 'packages/xprog-prensa-system/**'

jobs:
  Install-And-Build-Prensa-v2:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.1

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.npm
            # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-${{ hashFiles('**/xprog-prensa/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install
        run: yarn deps:prensa:sys

      - name: Build
        run: yarn build:prensa:sys
