name: prensa-bot ci
on: [push]

jobs:
  install_and_test:
    name: prensa-bot install and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16

      - name: pkg install
        run: npm install

      - name: pkg build
        run: npm run build

      - name: pkg lint
        run: npm run eslint
    
      - name: prensa-bot notify
        if: ${{ failure() }}
        run: pwd && ls -l && node ./notifications/ciNotification.js
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}