name: prensa-bot continuous-deploy
"on":
  push:
    branches:
      - master
jobs:
  release:
    name: prensa-bot deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16
      - run: npm install
      - run: npm run cd
      - run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: prensa-bot notify
        uses: slackapi/slack-github-action@v1.17.0